server:
  port: 8080
  session:

  servlet:
    session:
      cookie:
        path: /

spring:
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url:
      username:
      password:

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  redis:
    host: localhost

    database: 0
    port: 6379
    password: #123456

#    cluster:
#      nodes:
#        - 192.168.0.119:6379
#        - 192.168.0.119:6380
#        - 192.168.0.108:6379
#        - 192.168.0.108:6380
#        - 192.168.0.111:6379
#        - 192.168.0.111:6380
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 3000


  elasticsearch:
    repositories:
      enabled: true
    cluster-nodes:

  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5
    cache: false

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  aop:
    auto: true
    proxy-target-class: true

redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120

jwt:
  tokenHeader: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: Bearer

elasticsearch:
  ip:

databaseAndTable:
  database1:comments;database2:ums_member
async:
  executor:
    thread:
      core_pool_size : 10
      max_pool_size : 50
      queue_capacity : 10000
      keep_alive_seconds : 300