server:
  port: 8080
  session:

  servlet:
    session:
      cookie:
        path: /

spring:
  datasource:
    #    druid:
    #      db-type: com.alibaba.druid.pool.DruidDataSource
    #      driver-class-name: oracle.jdbc.OracleDriver
    #      url: jdbc:oracle:thin:@172.16.4.5:1521/xz2000.nrcloud.hb
    #      username: xz2017
    #      password: xz2017
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  redis:
    host: localhost
    #host: 172.16.4.136
    database: 0
    port: 6379
    password: #123456

#    cluster:
#      nodes:
#        - 192.168.0.119:6379
#        - 192.168.0.119:6380
#        - 192.168.0.108:6379
#        - 192.168.0.108:6380
#        - 192.168.0.111:6379
#        - 192.168.0.111:6380
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 3000


  elasticsearch:
    repositories:
      enabled: true
    cluster-nodes:
      #172.16.4.136:9200
      120.79.149.109:9200

  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5
    cache: false

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  aop:
    auto: true
    proxy-target-class: true

redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120

jwt:
  tokenHeader: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: Bearer

elasticsearch:
  ip:
    #127.0.0.1:9200,127.0.0.2:9200,127.0.0.3:9200,127.0.0.4:9200,127.0.0.5:9200,127.0.0.6:9200
    #172.16.4.136:9200
    120.79.149.109:9200

mybatis:
  mapper-locations:
  - classpath:wuhan/*.xml
  - classpath*:wuhan/mapper3/*.xml
databaseAndTable:
  database1:comments;database2:ums_member